IF NOT DEFINED CM_CURRENT_SCRIPT_PATH SET CM_CURRENT_SCRIPT_PATH=%CD%

%CM_PYTHON_BIN% %CM_CURRENT_SCRIPT_PATH%\code.py
IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%

echo CM_NEW_VAR_FROM_RUN=XYZ > tmp-run-env.out
